apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "chmod 777 -R /var/lib/grafana/"]
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana/
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-auth
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-auth
                  key: password
          ports:
            - containerPort: 3000
          volumeMounts:  # Add this section for volume mount
            - name: grafana-data
              mountPath: /var/lib/grafana
      nodeSelector:
        kubernetes.io/hostname: slave-3
      volumes:  # Add this section for defining the volume
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-claim 
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
data:
  username: *****
  password: *****
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-claim  # Sets name of PVC
  labels:
    app: grafana
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size
  volumeName: grafana-volume
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: grafana
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/grafana/"