apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  volumes:
    - name: prometheus-data
      persistentVolumeClaim:
        claimName: prometheus-pvc
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "chmod 777 -R /prometheus"]
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.30.0
          ports:
            - containerPort: 9090
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      nodeSelector:
        kubernetes.io/hostname: slave-3
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'dashboard-metric'
        static_configs:
          - targets: ['49.13.66.198:10250']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 5Gi  # Adjust storage size based on your requirements
  accessModes:
    - ReadWriteOnce  # Adjust based on your requirements
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-storage-class  # Replace with your StorageClass name
  hostPath:
    path: /mnt/prometheus-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Should match the PV's accessModes
  resources:
    requests:
      storage: 5Gi  # Should match the PV's capacity
  storageClassName: prometheus-storage-class 